// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var TelegramBot, lessons, my_date, tb, token;

  lessons = require('./lessons');

  my_date = require('./my_date');

  TelegramBot = require('node-telegram-bot-api');

  token = '';

  tb = new TelegramBot(token, {
    polling: true
  });

  tb.on('message', function(msg) {
    var chatId;
    chatId = msg.chat.id;
    console.log(msg.text);
    return my_date.to_date(msg.text, function(err, out_date) {
      if (err) {
        throw err;
      }
      return lessons.day(new Date(out_date).getDay(), function(err, data) {
        if (err) {
          throw err;
        }
        return console.log(data);
      });
    });
  });

}).call(this);
