// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var TZO, dictionaryDate, getNumberLessonsWeek, toDate;

  dictionaryDate = {
    '0': 'Воскресенье',
    '1': 'Понедельник',
    '2': 'Вторник',
    '3': 'Среда',
    '4': 'Четверг',
    '5': 'Пятница',
    '6': 'Суббота'
  };

  TZO = (new Date().getTimezoneOffset() * -1) * 1000 * 60;

  getNumberLessonsWeek = function(callback) {
    var end, start;
    start = (new Date(2016, 7, 28, 0, 0, 0).getTime()) + TZO;
    end = (new Date().getTime()) + TZO;
    return callback(Math.ceil(((end - start) / (1000 * 60 * 60 * 24)) / 7));
  };

  toDate = function(date, callback) {
    var newDate;
    if (isNaN(new Date(Date.parse(date)))) {
      return callback('Дата не верна: ' + date);
    } else {
      newDate = (new Date(date).getTime()) + TZO;
      return callback(null, newDate);
    }
  };

  module.exports = {
    int_week: getNumberLessonsWeek,
    dic_date: dictionaryDate,
    to_date: toDate
  };

}).call(this);
