// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var TZO, dictionary_DayWeek, dictionary_Months, dictionary_TimeLessons, dictionary_ru_to_eng, endDay, getNumberLessonsWeek, startDay, startWeek, toDate;

  dictionary_DayWeek = {
    '0': 'Воскресенье',
    '1': 'Понедельник',
    '2': 'Вторник',
    '3': 'Среда',
    '4': 'Четверг',
    '5': 'Пятница',
    '6': 'Суббота'
  };

  dictionary_ru_to_eng = {
    'января': 'jan',
    'февраля': 'feb',
    'марта': 'mar',
    'апреля': 'apr',
    'мая': 'may',
    'июня': 'jun',
    'июля': 'jul',
    'августа': 'aug',
    'сентября': 'sep',
    'октября': 'oct',
    'ноября': 'nov',
    'декабря': 'dec'
  };

  dictionary_Months = {
    '0': 'Января',
    '1': 'Февраля',
    '2': 'Марта',
    '3': 'Апреля',
    '4': 'Мая',
    '5': 'Июня',
    '6': 'Июля',
    '7': 'Августа',
    '8': 'Сентября',
    '9': 'Октября',
    '10': 'Ноября',
    '11': 'Декабря'
  };

  dictionary_TimeLessons = {
    '1': '8:30-10:00',
    '2': '10:10-11:40',
    '3': '11:50-13:20',
    '4': '13:50-15:20',
    '5': '15:30-17:00',
    '6': '17:10-18:40'
  };

  startWeek = new Date(2016, 7, 28, 0, 0, 0);

  startDay = new Date(2016, 8, 1, 0, 0, 0);

  endDay = new Date(2017, 0, 31, 0, 0, 0);

  TZO = (new Date().getTimezoneOffset() * -1) * 1000 * 60;

  getNumberLessonsWeek = function(date, callback) {
    var end, start;
    if (isNaN(new Date(Date.parse(date)))) {
      callback('Дата не верна. Введите дату в формате: день месяц год');
    }
    start = (startWeek.getTime()) + TZO;
    end = (new Date(date).getTime()) + TZO;
    return callback(null, Math.ceil(((end - start) / (1000 * 60 * 60 * 24)) / 7));
  };

  toDate = function(date, callback) {
    var arr_date, code_week_fn, day_week, in_date, new_date;
    if (typeof date !== 'object') {
      arr_date = date.split(' ');
      if (dictionary_ru_to_eng[arr_date[1]] !== void 0 && arr_date.length !== 1) {
        date = arr_date[0] + ' ' + dictionary_ru_to_eng[arr_date[1]] + ' ' + arr_date[2];
      }
      if (arr_date[2] === void 0 && arr_date.length !== 1) {
        if (dictionary_ru_to_eng[arr_date[1]] !== void 0 && arr_date.length !== 1) {
          date = arr_date[0] + ' ' + dictionary_ru_to_eng[arr_date[1]] + ' 2016';
        } else {
          date = arr_date[0] + ' ' + arr_date[1] + ' 2016';
        }
      }
    }
    if (isNaN(new Date(Date.parse(date)))) {
      callback('<b>Дата не верна. Введите дату в формате: день месяц год</b>');
    }
    in_date = new Date(date).getTime();
    if (in_date <= startDay.getTime() || in_date >= endDay.getTime()) {
      callback('<b>Дата не входит в учебный семестр. Введите дату в формате: день месяц год</b>');
    }
    new_date = new Date((new Date(date).getTime()) + TZO);
    day_week = new_date.getDay();
    code_week_fn = getNumberLessonsWeek(new_date, function(err, data) {
      if (err) {
        throw err;
      }
      if (day_week === 0) {
        return data - 1;
      }
      return data;
    });
    return callback(null, {
      newDate: new_date,
      dayWeek: day_week,
      codeWeek: code_week_fn,
      evenWeek: code_week_fn % 2
    });
  };

  module.exports = {
    int_week: getNumberLessonsWeek,
    dic_date: dictionary_DayWeek,
    dic_month: dictionary_Months,
    dic_timeLessons: dictionary_TimeLessons,
    to_date: toDate
  };

}).call(this);
